name: 'CodeBoarding [Diagram-First Documentation]'
description: 'Generates diagram-first visualizations of your codebase using static analysis and large language models.'
author: 'CodeBoarding'

branding:
  icon: 'book-open'  # or 'layers', 'git-branch', 'book-open', 'target'
  color: 'blue'

inputs:
  output_directory:
    description: 'Directory where documentation files will be saved'
    required: false
    default: 'docs'
  
  repository_url:
    description: 'Repository URL to fetch documentation for (defaults to current repository)'
    required: true

outputs:
  markdown_files_created:
    description: 'Number of Markdown files created'
    value: ${{ steps.process-docs.outputs.markdown_files_created }}
  
  json_files_created:
    description: 'Number of JSON files created'
    value: ${{ steps.process-docs.outputs.json_files_created }}
  
  output_directory:
    description: 'Directory where Markdown files were saved'
    value: ${{ steps.process-docs.outputs.output_directory }}
  
  json_directory:
    description: 'Directory where JSON files were saved (.codeboarding)'
    value: ${{ steps.process-docs.outputs.json_directory }}
  
  has_changes:
    description: 'Whether any files were created or changed'
    value: ${{ steps.process-docs.outputs.has_changes }}

runs:
  using: 'composite'
  steps:
    - name: Determine repository URL
      id: repo-url
      shell: bash
      run: |
        if [ "${{ inputs.repository_url }}" != "" ]; then
          REPO_URL="${{ inputs.repository_url }}"
          echo "Using provided repository URL: $REPO_URL"
        else
          REPO_URL="${{ github.server_url }}/${{ github.repository }}"
          echo "Using current repository URL: $REPO_URL"
        fi
        echo "repo_url=$REPO_URL" >> $GITHUB_OUTPUT

    - name: Fetch documentation files
      id: fetch-docs
      shell: bash
      run: |
        ENDPOINT_URL="https://server.codeboarding.org/github_action"
        REPO_URL="${{ steps.repo-url.outputs.repo_url }}"
        
        echo "Fetching documentation from: $ENDPOINT_URL?url=$REPO_URL"
        
        # Create temporary file for response
        TEMP_FILE=$(mktemp)
        
        # Make the API call and save response
        response=$(curl -s -w "%{http_code}" -o "$TEMP_FILE" "$ENDPOINT_URL?url=$REPO_URL")
        http_code=${response: -3}
        
        if [ "$http_code" != "200" ]; then
          echo "Error: API call failed with status code $http_code"
          cat "$TEMP_FILE"
          rm -f "$TEMP_FILE"
          exit 1
        fi
        
        # Check if response is valid JSON
        if ! jq empty "$TEMP_FILE" 2>/dev/null; then
          echo "Error: Invalid JSON response"
          cat "$TEMP_FILE"
          rm -f "$TEMP_FILE"
          exit 1
        fi
        
        echo "API call successful"
        echo "response_file=$TEMP_FILE" >> $GITHUB_OUTPUT

    - name: Process documentation files
      id: process-docs
      shell: bash
      run: |
        RESPONSE_FILE="${{ steps.fetch-docs.outputs.response_file }}"
        MD_OUTPUT_DIR="${{ inputs.output_directory }}"
        JSON_OUTPUT_DIR=".codeboarding"
        
        # Create the output directories
        mkdir -p "$MD_OUTPUT_DIR"
        mkdir -p "$JSON_OUTPUT_DIR"
        
        # Initialize counters
        MARKDOWN_FILES_CREATED=0
        JSON_FILES_CREATED=0
        
        echo "=== Processing Documentation Files ==="
        echo "Response JSON structure:"
        jq . "$RESPONSE_FILE"
        
        # Parse JSON response and create files using keys as filenames
        if jq -e '.files' "$RESPONSE_FILE" > /dev/null; then
          echo "Files key found, proceeding to create files..."
          
          # Get each key from files object and create a file with that name
          jq -r '.files | keys[]' "$RESPONSE_FILE" | while read -r filename; do
            echo "Processing file: $filename"
            
            # Get the content for this filename
            content=$(jq -r ".files[\"$filename\"]" "$RESPONSE_FILE")
            
            # Determine file type and destination
            if [[ "$filename" == *.json ]]; then
              # JSON file
              output_dir="$JSON_OUTPUT_DIR"
              output_filename="$filename"
              echo "$content" > "$output_dir/$output_filename"
              echo "Created JSON file: $output_dir/$output_filename"
              JSON_FILES_CREATED=$((JSON_FILES_CREATED + 1))
            else
              # Markdown file - add .md extension if not present
              output_dir="$MD_OUTPUT_DIR"
              if [[ "$filename" != *.md ]]; then
                output_filename="${filename}.md"
              else
                output_filename="$filename"
              fi
              echo "$content" > "$output_dir/$output_filename"
              echo "Created Markdown file: $output_dir/$output_filename"
              MARKDOWN_FILES_CREATED=$((MARKDOWN_FILES_CREATED + 1))
            fi
          done
          
          # Since we're in a subshell, we need to count files differently
          MARKDOWN_FILES_CREATED=$(find "$MD_OUTPUT_DIR" -name "*.md" 2>/dev/null | wc -l || echo "0")
          JSON_FILES_CREATED=$(find "$JSON_OUTPUT_DIR" -name "*.json" 2>/dev/null | wc -l || echo "0")
        else
          echo "No 'files' key found in response JSON"
        fi
        
        # Clean up temporary file
        rm -f "$RESPONSE_FILE"
        
        # Check if any files were created
        TOTAL_FILES=$((MARKDOWN_FILES_CREATED + JSON_FILES_CREATED))
        if [ "$TOTAL_FILES" -gt 0 ]; then
          HAS_CHANGES="true"
          echo "Created $MARKDOWN_FILES_CREATED Markdown files in $MD_OUTPUT_DIR"
          echo "Created $JSON_FILES_CREATED JSON files in $JSON_OUTPUT_DIR"
          
          # List created files
          if [ "$MARKDOWN_FILES_CREATED" -gt 0 ]; then
            echo "Markdown files created:"
            ls -la "$MD_OUTPUT_DIR"
          fi
          
          if [ "$JSON_FILES_CREATED" -gt 0 ]; then
            echo "JSON files created:"
            ls -la "$JSON_OUTPUT_DIR"
          fi
        else
          HAS_CHANGES="false"
          echo "No files were created"
        fi
        
        # Set outputs
        echo "markdown_files_created=$MARKDOWN_FILES_CREATED" >> $GITHUB_OUTPUT
        echo "json_files_created=$JSON_FILES_CREATED" >> $GITHUB_OUTPUT
        echo "output_directory=$MD_OUTPUT_DIR" >> $GITHUB_OUTPUT
        echo "json_directory=$JSON_OUTPUT_DIR" >> $GITHUB_OUTPUT
        echo "has_changes=$HAS_CHANGES" >> $GITHUB_OUTPUT
